import js from "@eslint/js";
import vue from "eslint-plugin-vue";
import typescript from "@typescript-eslint/eslint-plugin";
import parser from "@typescript-eslint/parser";
import vueParser from "vue-eslint-parser";

export default [
  js.configs.recommended,
  ...vue.configs["flat/recommended"],
  {
    files: ["**/*.vue", "**/*.ts", "**/*.tsx"],
    languageOptions: {
      parser: vueParser,
      parserOptions: {
        parser: parser,
        sourceType: "module",
        ecmaVersion: "latest",
      },
      globals: {
        defineNuxtPlugin: "readonly",
        defineEventHandler: "readonly",
        defineCachedEventHandler: "readonly",
        defineNitroPlugin: "readonly",
        useRoute: "readonly",
        useRouter: "readonly",
        useFetch: "readonly",
        useAsyncData: "readonly",
        useHead: "readonly",
        useCookie: "readonly",
        useStorage: "readonly",
        useState: "readonly",
        useRuntimeConfig: "readonly",
        useRequestEvent: "readonly",
        useRequestHeaders: "readonly",
        useResponseHeader: "readonly",
        refreshCookie: "readonly",
        getCookie: "readonly",
        setCookie: "readonly",
        getHeader: "readonly",
        getHeaders: "readonly",
        getQuery: "readonly",
        getRouterParam: "readonly",
        readBody: "readonly",
        readMultipartBody: "readonly",
        readRawBody: "readonly",
        getRequestURL: "readonly",
        getRequestProtocol: "readonly",
        getRequestHost: "readonly",
        getResponseStatus: "readonly",
        getResponseStatusText: "readonly",
        setResponseStatus: "readonly",
        sendRedirect: "readonly",
        sendNoContent: "readonly",
        sendStream: "readonly",
        sendWebResponse: "readonly",
        isMethod: "readonly",
        assertMethod: "readonly",
        requireMethod: "readonly",
        getMethod: "readonly",
        createError: "readonly",
        sendError: "readonly",
        $fetch: "readonly",
        useNuxtApp: "readonly",
        useAppConfig: "readonly",
        useRuntimeHook: "readonly",
        onPrehydrate: "readonly",
        onMounted: "readonly",
        onUnmounted: "readonly",
        onBeforeMount: "readonly",
        onBeforeUnmount: "readonly",
        ref: "readonly",
        reactive: "readonly",
        computed: "readonly",
        watch: "readonly",
        watchEffect: "readonly",
        watchDeep: "readonly",
        watchImmediate: "readonly",
        watchOnce: "readonly",
        watchPausable: "readonly",
        toRef: "readonly",
        toRefs: "readonly",
        toValue: "readonly",
        unref: "readonly",
        isRef: "readonly",
        shallowRef: "readonly",
        shallowReactive: "readonly",
        triggerRef: "readonly",
        customRef: "readonly",
        provide: "readonly",
        inject: "readonly",
        defineProps: "readonly",
        defineEmits: "readonly",
        defineExpose: "readonly",
        defineModel: "readonly",
        defineOptions: "readonly",
        defineSlots: "readonly",
        useSlots: "readonly",
        useAttrs: "readonly",
        useModel: "readonly",
        useTemplateRef: "readonly",
        withDefaults: "readonly",
        nextTick: "readonly",
        console: "readonly",
        process: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        fetch: "readonly",
        URLSearchParams: "readonly",
        TextEncoder: "readonly",
        TextDecoder: "readonly",
        URL: "readonly",
        Buffer: "readonly",
        crypto: "readonly",
        confirm: "readonly",
        alert: "readonly",
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        NodeJS: "readonly",
      },
    },
    plugins: {
      "@typescript-eslint": typescript,
    },
    rules: {
      "vue/multi-word-component-names": "off",
      "vue/valid-v-slot": [
        "error",
        {
          allowModifiers: true,
        },
      ],
      "vue/no-v-html": "off",
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      "no-unused-vars": "off",
      "no-undef": "off",
      "no-empty": [
        "warn",
        {
          allowEmptyCatch: true,
        },
      ],
    },
  },
  {
    ignores: [".nuxt/**", ".output/**", "node_modules/**"],
  },
];
